import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

export default function PrivacyPolicy() {
    return (
        <div style={{ minHeight: '100vh', background: '#f5f5f5', display: 'flex', flexDirection: 'column' }}>
            <Navbar />
            <div style={{ maxWidth: '720px', margin: '0 auto', padding: '48px 24px', flex: 1 }}>
                <h1 style={{ fontSize: '28px', fontWeight: '700', marginBottom: '8px', color: '#1a1a1a' }}>
                    Privacy Policy
                </h1>
                <p style={{ fontSize: '13px', color: '#888', marginBottom: '40px' }}>
                    Last updated: March 31, 2026
                </p>

                <Section title="1. Information we collect">
                    When you register for CheckoutAlert, we collect your email address and password.
                    When you add endpoints to monitor, we store the URLs, HTTP methods, alert email
                    addresses, and any custom headers you provide. We also store ping results,
                    latency data, and incident history generated by monitoring your endpoints.
                </Section>

                <Section title="2. How we use your information">
                    We use your email address to send you alert notifications when your monitored
                    APIs behave abnormally, and to send OTP codes for authentication. We use your
                    endpoint data solely to perform the monitoring service you have configured.
                    We do not sell, rent, or share your data with third parties for marketing purposes.
                </Section>

                <Section title="3. Data storage">
                    Your data is stored in secured databases hosted on Railway (MySQL) and
                    Upstash (Redis). Passwords are hashed using BCrypt and are never stored
                    in plaintext. Auth tokens are stored in httpOnly cookies and are not
                    accessible to JavaScript.
                </Section>

                <Section title="4. Third-party services">
                    CheckoutAlert uses the following third-party services to operate:
                    Google Gemini AI for generating root cause analysis of incidents,
                    Gmail SMTP for sending alert and OTP emails, Railway for database
                    hosting, and Upstash for Redis cache hosting. Each service has its
                    own privacy policy governing how they handle data.
                </Section>

                <Section title="5. Data retention">
                    We retain your account data for as long as your account is active.
                    Ping results are retained indefinitely to provide historical uptime data.
                    You may delete your account and all associated data at any time by
                    contacting us at checkoutalertt@gmail.com.
                </Section>

                <Section title="6. Security">
                    We implement industry-standard security measures including BCrypt password
                    hashing, httpOnly cookies for token storage, HTTPS-only communication,
                    OTP-based two-factor authentication, IP-based rate limiting, and
                    input validation on all endpoints. However, no system is completely
                    secure and we cannot guarantee absolute security.
                </Section>

                <Section title="7. Your rights">
                    You have the right to access, correct, or delete your personal data.
                    To exercise these rights, contact us at checkoutalertt@gmail.com.
                    We will respond to all requests within 30 days.
                </Section>

                <Section title="8. Changes to this policy">
                    We may update this Privacy Policy from time to time. We will notify
                    you of significant changes by email. Continued use of CheckoutAlert
                    after changes constitutes acceptance of the updated policy.
                </Section>

                <Section title="9. Contact">
                    If you have any questions about this Privacy Policy, contact us at{' '}
                    <a href="mailto:checkoutalertt@gmail.com" style={{ color: '#1a1a1a' }}>
                        checkoutalertt@gmail.com
                    </a>.
                </Section>
            </div>
            <Footer />
        </div>
    );
}

function Section({ title, children }) {
    return (
        <div style={{ marginBottom: '32px' }}>
            <h2 style={{
                fontSize: '16px', fontWeight: '600',
                color: '#1a1a1a', marginBottom: '10px'
            }}>
                {title}
            </h2>
            <p style={{
                fontSize: '14px', color: '#555',
                lineHeight: '1.8', margin: 0
            }}>
                {children}
            </p>
        </div>
    );
}